#!/bin/bash

. /etc/bahmni-installer/bahmni.conf

echo "Running bahmni-export..."
java -DstartDate=2016-10-01 -DendDate=2017-05-31 -DOPENMRS_DB_SERVER=${OPENMRS_DB_SERVER} -DOPENMRS_DB_USER=${OPENMRS_DB_USERNAME} -DOPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD} -jar /opt/bahmni-export/libs/bahmni-export-*.jar >> /opt/bahmni-export/log/bahmni-export.log
echo "Done"
